[project]
name = "funasr-my-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "funasr>=1.3.0",
    "numpy<2.0",
    "pyaudio>=0.2.14",
    "torch==2.2.1",
    "torchaudio>=2.2.1",
]
